SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE AGE IS NULL;

/*
1단계
SELECT USER_ID, GENDER, AGE, JOINED
FROM USER_INFO

2단계
SELECT USER_ID, GENDER, AGE, DATE_FORMAT(JOINED, '%Y-%m-%d')AS JOINED
FROM USER_INFO
WHERE AGE IS NULL;

3단계
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE AGE = NULL;

*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/131528 */