SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID ASC;

/*
1단계
SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME
FROM ANIMAL_INS;


2단계
SELECT ANIMAL_ID, ANIMAL_TYPE, DATE_FORMAT(DATETIME,'%Y-%m-%d') AS DATETIME, INTAKE_CONDITION, NAME
FROM ANIMAL_INS;

3단계
SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC;

4단계
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID ASC;


*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/59407 */