SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC;

/*
1단계
SELECT SHIPMENT_ID,	FLAVOR,	TOTAL_ORDER
FROM FIRST_HALF;

2단계
SELECT SHIPMENT_ID,	FLAVOR,	TOTAL_ORDER
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC;

3단계
SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC;

*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/133024 */