SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL AND GENDER = 'W' AND DATE_OF_BIRTH LIKE "%03%"
ORDER BY MEMBER_ID ASC;

/*
1단계
SELECT MEMBER_ID, MEMBER_NAME, TLNO,	GENDER, DATE_OF_BIRTH
FROM MEMBER_PROFILE;

2단계
SELECT MEMBER_ID, MEMBER_NAME, TLNO,	GENDER, DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL;

3단계
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;

4단계
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL AND GENDER = 'W' AND DATE_OF_BIRTH LIKE "%03%"
ORDER BY MEMBER_ID ASC;

*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/131120 */