SELECT ANIMAL_TYPE, 
       COALESCE(NULLIF(NAME, ''), 'No name') AS NAME, 
       SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;


/*
1단계
SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS;

2단계
SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

3단계
SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME LIKE "NULL" = "No name"
ORDER BY ANIMAL_ID;

4단계 - 안됨 -
SELECT ANIMAL_TYPE, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE IF(NAME LIKE "NULL") NAME == "No name"
ORDER BY ANIMAL_ID;

5단계 - 됨 -
// 1번 COALESCE
SELECT ANIMAL_TYPE, 
       COALESCE(NULLIF(NAME, ''), 'No name') AS NAME, 
       SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;


// 2번 CASE
SELECT ANIMAL_TYPE, 
       CASE 
           WHEN NAME IS NULL THEN 'No name' 
           ELSE NAME 
       END AS NAME,
       SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

 */

/* https://school.programmers.co.kr/learn/courses/30/lessons/59410 */