SELECT COUNT(*) AS count
FROM ANIMAL_INS;

/*
1단계
SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS;

2단계
SELECT COUNT(*) AS count
FROM ANIMAL_INS;

*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/59406 */