SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ("Lucy","Ella","Pickle"," Rogan","Sabrina","Mitty")
ORDER BY ANIMAL_ID ASC;

/*
1단계
SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION,NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS;

2단계
SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION,NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC;

3단계
1번째 방법
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME LIKE "Lucy" OR NAME LIKE "Ella" OR NAME LIKE "Pickle" OR NAME LIKE " Rogan" OR NAME LIKE "Sabrina" OR NAME LIKE "Mitty"
ORDER BY ANIMAL_ID ASC;

2번째 방법
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ("Lucy","Ella","Pickle"," Rogan","Sabrina","Mitty")
ORDER BY ANIMAL_ID ASC;

*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/59046 */