SELECT  COUNT(FI.ID) AS FISH_COUNT,FNI.FISH_NAME
FROM  FISH_INFO AS FI
INNER JOIN  FISH_NAME_INFO AS FNI
    ON  FI.FISH_TYPE = FNI.FISH_TYPE
 GROUP BY  FISH_NAME
 ORDER BY  FISH_COUNT DESC;

/*
1단계
SELECT ID, FISH_TYPE, LENGTH, TIME
FROM FISH_INFO;

SELECT FISH_TYPE, FISH_NAME
FROM FISH_NAME_INFO;

2단계


3단계


*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/293257 */