SELECT 
    p.PRODUCT_CODE,
    SUM(p.PRICE * os.SALES_AMOUNT) AS SALES
FROM 
    PRODUCT p
INNER JOIN 
    OFFLINE_SALE os ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY 
    p.PRODUCT_CODE
ORDER BY 
    SALES DESC,
    p.PRODUCT_CODE ASC;

/* 
1단계
PRODUCT 테이블 조회
SELECT PRODUCT_ID, PRODUCT_CODE, PRICE
FROM PRODUCT;

OFFLINE_SALE 테이블 조회
SELECT OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM OFFLINE_SALE;


2단계
SELECT 
    p.PRODUCT_CODE,
    SUM(p.PRICE * os.SALES_AMOUNT) AS SALES
FROM 
    PRODUCT p
INNER JOIN 
    OFFLINE_SALE os ON p.PRODUCT_ID = os.PRODUCT_ID

3단계
SELECT 
    p.PRODUCT_CODE,
    SUM(p.PRICE * os.SALES_AMOUNT) AS SALES
FROM 
    PRODUCT p
INNER JOIN 
    OFFLINE_SALE os ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY 
    p.PRODUCT_CODE
 
4단계
SELECT 
    p.PRODUCT_CODE,
    SUM(p.PRICE * os.SALES_AMOUNT) AS SALES
FROM 
    PRODUCT p
INNER JOIN 
    OFFLINE_SALE os ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY 
    p.PRODUCT_CODE
ORDER BY 
    SALES DESC,
    p.PRODUCT_CODE ASC;
   
*/



/* https://school.programmers.co.kr/learn/courses/30/lessons/131533 */