SELECT 
     YEAR(YM) AS YEAR,
    ROUND(AVG(PM_VAL1), 2) AS 'PM10',
    ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
FROM 
    AIR_POLLUTION
WHERE 
    LOCATION2 = '수원'
GROUP BY 
    YEAR(YM)
ORDER BY 
    YEAR ASC;

/*
1단계
SELECT LOCATION1, LOCATION2, YM, PM_VAL1, PM_VAL2
FROM AIR_POLLUTION;

2단계
SELECT 
    SUBSTRING(YM, 1, 4) AS YEAR,
    ROUND(AVG(PM_VAL1), 2) AS PM10,
    ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
FROM 
    AIR_POLLUTION
GROUP BY 
    SUBSTRING(YM, 1, 4)
ORDER BY YEAR ASC;

3단계
SELECT 
    SUBSTRING(YM, 1, 4) AS YEAR,
    ROUND(AVG(PM_VAL1), 2) AS PM10,
    ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
FROM 
    AIR_POLLUTION
WHERE 
    LOCATION2 = '수원'
GROUP BY 
    SUBSTRING(YM, 1, 4)
ORDER BY 
    YEAR ASC;
ㄴ> 서브스트링 쓰면 틀렸다고 나옴...

SELECT 
     YEAR(YM) AS YEAR,
    ROUND(AVG(PM_VAL1), 2) AS 'PM10',
    ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
FROM 
    AIR_POLLUTION
WHERE 
    LOCATION2 = '수원'
GROUP BY 
    YEAR(YM)
ORDER BY 
    YEAR ASC;


*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/284530 */