SELECT  COUNT(ID) AS FISH_COUNT, MONTH(TIME) AS MONTH
FROM  FISH_INFO
GROUP BY  MONTH(TIME)
ORDER BY  MONTH;

/*
1단계
SELECT ID, FISH_TYPE, LENGTH, TIME
FROM FISH_INFO;

2단계
SELECT  COUNT(ID) AS FISH_COUNT, MONTH(TIME) AS MONTH
FROM  FISH_INFO
GROUP BY  MONTH(TIME)
ORDER BY  MONTH;

*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/293260 */