SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE TIME(DATETIME) BETWEEN '09:00:00' AND '19:59:59'
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME) ASC;

/*
1단계
SELECT DATETIME AS HOUR
FROM ANIMAL_OUTS
WHERE TIME(DATETIME) BETWEEN '09:00:00' AND '19:59:59'
ORDER BY DATETIME ASC;

2단계
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE TIME(DATETIME) BETWEEN '09:00:00' AND '19:59:59'
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME) ASC;

*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/59412 */