SELECT 
    CAR_ID, 
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 
    CAR_ID
HAVING 
    AVERAGE_DURATION >= 7
ORDER BY 
    AVERAGE_DURATION DESC, CAR_ID DESC;
    
/*
1단계
SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY;

2단계
SELECT 
    CAR_ID, 
    IF(END_DATE - START_DATE >= 7, 'TRUE', 'FALSE') AS AVERAGE_DURATION
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY;


3단계
SELECT 
    CAR_ID, 
    ROUND(AVG(END_DATE - START_DATE), 1) AS AVERAGE_DURATION
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    END_DATE - START_DATE >= 7
GROUP BY 
    CAR_ID;
    
4단계
SELECT 
    CAR_ID, 
    ROUND(AVG(END_DATE - START_DATE), 1) AS AVERAGE_DURATION
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    END_DATE - START_DATE >= 7
GROUP BY 
    CAR_ID
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

틀렸다고 나옴...

5단계
SELECT 
    CAR_ID, 
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 
    CAR_ID
HAVING 
    AVERAGE_DURATION >= 7
ORDER BY 
    AVERAGE_DURATION DESC, CAR_ID DESC;
    
정답...

*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/157342 */