SELECT DISTINCT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID AND A.PRODUCT_ID = B.PRODUCT_ID AND A.ONLINE_SALE_ID != B.ONLINE_SALE_ID
ORDER BY A.USER_ID ASC, A.PRODUCT_ID DESC;

/*
1단계
SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM ONLINE_SALE;


2단계
SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE 
FROM ONLINE_SALE;


3단계
SELECT DISTINCT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID AND A.PRODUCT_ID = B.PRODUCT_ID AND A.ONLINE_SALE_ID != B.ONLINE_SALE_ID
ORDER BY A.USER_ID ASC, A.PRODUCT_ID DESC;

 */



/* https://school.programmers.co.kr/learn/courses/30/lessons/131536 */