SELECT SUM(HG.SCORE) AS SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_DEPARTMENT HD
INNER JOIN HR_EMPLOYEES HE
ON HD.DEPT_ID = HE.DEPT_ID
INNER JOIN HR_GRADE HG
ON HG.EMP_NO = HE.EMP_NO

GROUP BY HG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;

/*
1단계
SELECT DEPT_ID, DEPT_NAME_KR, DEPT_NAME_EN, LOCATION
FROM HR_DEPARTMENT;

SELECT EMP_NO, EMP_NAME, DEPT_ID, POSITION, EMAIL, COMP_TEL, HIRE_DATE, SAL
FROM HR_EMPLOYEES;

SELECT EMP_NO, YEAR, HALF_YEAR, SCORE
FROM HR_GRADE;

2단계
SELECT SUM(HG.SCORE) AS SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_DEPARTMENT HD
INNER JOIN HR_EMPLOYEES HE
ON HD.DEPT_ID = HE.DEPT_ID
INNER JOIN HR_GRADE HG
ON HG.EMP_NO = HE.EMP_NO

GROUP BY HG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;


어렵다...
*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/284527 */