SELECT count(DISTINCT NAME) AS count
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;

/*
1단계
SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION , NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS;

2단계 안됨
SELECT DISTINCT count(NAME) AS count
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;

3단계
//1.
SELECT count(distinct name)
FROM ANIMAL_INS;

//2.
SELECT count(DISTINCT NAME) AS count
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;


 */

/* https://school.programmers.co.kr/learn/courses/30/lessons/59408 */