SELECT  LEFT(PRODUCT_CODE, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY 
LEFT(PRODUCT_CODE, 2)
ORDER BY CATEGORY ASC;

/* ORDER BY 를 굳이 쓸 필요가 없나?? 안써도 정답으로 나오긴함. */

/*
1단계
SELECT PRODUCT_ID, PRODUCT_CODE, PRICE
FROM PRODUCT;

2단계
SELECT  LEFT(PRODUCT_CODE, 2) AS CATEGORY
FROM PRODUCT;

3단계
SELECT  LEFT(PRODUCT_CODE, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY 
LEFT(PRODUCT_CODE, 2);

4단계
SELECT  LEFT(PRODUCT_CODE, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY 
LEFT(PRODUCT_CODE, 2)
ORDER BY CATEGORY ASC;

*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/131529 */