SELECT COUNT(*) AS FISH_COUNT 
FROM FISH_INFO
WHERE LENGTH IS NULL;

/*
1단계
SELECT ID, FISH_TYPE, LENGTH, TIME
FROM FISH_INFO;

2단계
NULL 값을 10으로 반환

SELECT COALESCE(LENGTH,10) AS FISH COUNT
FROM FISH_INFO;

3단계
10이하인 값만 출력

SELECT COALESCE(LENGTH, 10) AS FISH_COUNT
FROM FISH_INFO
WHERE COALESCE(LENGTH, 10) <= 10;

4단계
10이하만 카운트해서 출력
85점
SELECT count(COALESCE(LENGTH, 10)) AS FISH_COUNT
FROM FISH_INFO
WHERE COALESCE(LENGTH, 10) <= 10;

85점
SELECT count(*) AS FISH_COUNT
FROM FISH_INFO
WHERE COALESCE(LENGTH, 10) <= 10;

정답
SELECT COUNT(*) AS FISH_COUNT 
FROM FISH_INFO
WHERE LENGTH IS NULL;

*/


/* https://school.programmers.co.kr/learn/courses/30/lessons/293258 */