SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY = '인문';


/*
1단계
BOOK 테이블 출력

SELECT BOOK_ID,	CATEGORY,AUTHOR_ID, PRICE, PUBLISHED_DATE
FROM BOOK;

2단계
BOOK 테이블에서 2021년에 출판된 '인문' 카테고리에 속하는 도서 리스트
SELECT BOOK_ID, PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY = '인문';

3단계
도서 ID(BOOK_ID), 출판일 (PUBLISHED_DATE)을 출력(년도 포맷 맞추기)
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY = '인문';


*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/144853 */