SELECT CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS like "%네비게이션%"
order by CAR_ID DESC;

/*
1단계
CAR_RENTAL_COMPANY_CAR 테이블 출력

SELECT CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
FROM CAR_RENTAL_COMPANY_CAR;

2단계
SELECT CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS like "%네비게이션%"

3단계
SELECT CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS like "%네비게이션%"
order by CAR_ID DESC;




 */



/* https://school.programmers.co.kr/learn/courses/30/lessons/157343 */