SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE SKILL_1 = "Python" OR SKILL_2 = "Python" OR SKILL_3 = "Python"
ORDER BY ID ASC;


/*
1단계
DEVELOPER_INFOS 테이블 출력

SELECT ID, FIRST_NAME, LAST_NAME, EMAIL
FROM DEVELOPER_INFOS;

2단계
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE SKILL_1 = "Python" OR SKILL_2 = "Python" OR SKILL_3 = "Python"
ORDER BY ID ASC;



*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/276013 */