SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, COALESCE(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME like "%경기%"
ORDER BY WAREHOUSE_ID ASC;
/*
1단계
FOOD_WAREHOUSE 테이블 출력
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, TLNO, COALESCE(FREEZER_YN, 'N')
FROM FOOD_WAREHOUSE;

2단계
경기도에 위치한
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, COALESCE(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME like "%경기%"


3단계
창고 ID 기준으로 오름차순 정렬
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, COALESCE(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME like "%경기%"
ORDER BY WAREHOUSE_ID ASC;


*/

/* https://school.programmers.co.kr/learn/courses/30/lessons/131114 */