SELECT A.TITLE,
       A.BOARD_ID,
       B.REPLY_ID,
       B.WRITER_ID,
       B.CONTENTS,
       DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS A
INNER 
 JOIN USED_GOODS_REPLY AS B
   ON A.BOARD_ID = B.BOARD_ID
WHERE SUBSTR(A.CREATED_DATE, 1, 7) = '2022-10'
ORDER 
   BY B.CREATED_DATE ASC, A.TITLE ASC;


/*
SELECT A.TITLE,
       A.BOARD_ID,
       B.REPLY_ID,
       B.WRITER_ID,
       B.CONTENTS,
       DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS A
INNER 
 JOIN USED_GOODS_REPLY AS B
   ON A.BOARD_ID = B.BOARD_ID
WHERE DATE_FORMAT(A.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER 
   BY B.CREATED_DATE ASC, A.TITLE ASC;
 */


/*
1단계
SELECT BOARD_ID, WRITER_ID, TITLE, CONTENTS, PRICE, DATE_FORMAT(CREATED_DATE, '%Y-%m-%d'), STATUS, VIEWS
FROM USED_GOODS_BOARD;

2단계
SELECT BOARD_ID, WRITER_ID, TITLE, CONTENTS, PRICE, DATE_FORMAT(CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE, STATUS, VIEWS
FROM USED_GOODS_BOARD
UNION
SELECT REPLY_ID, BOARD_ID, WRITER_ID, CONTENTS, DATE_FORMAT(CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY;

3단계
SELECT TITLE, BOARD_ID, REPLY_ID, WRITER_ID, CONTENTS, DATE_FORMAT(CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD
UNION
SELECT TITLE, BOARD_ID, REPLY_ID, WRITER_ID, CONTENTS, DATE_FORMAT(CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY;


4단계
SELECT b.TITLE AS 게시글_제목,
       b.BOARD_ID AS 게시글_ID,
       r.REPLY_ID AS 댓글_ID,
       r.WRITER_ID AS 댓글_작성자_ID,
       r.CONTENTS AS 댓글_내용,
       DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS 댓글_작성일
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
WHERE DATE_FORMAT(r.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;


5단계
SELECT b.TITLE,
       b.BOARD_ID,
       r.REPLY_ID,
       r.WRITER_ID,
       r.CONTENTS,
       DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD b
INNER JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
WHERE DATE_FORMAT(r.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;




SELECT  A.TITLE
        , A.BOARD_ID
        , B.REPLY_ID
        , B.WRITER_ID
        , B.CONTENTS
        , DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CRAETED_DATE
  FROM  USED_GOODS_BOARD AS A
 INNER
  JOIN  USED_GOODS_REPLY AS B
    ON  A.BOARD_ID = B.BOARD_ID
 WHERE  SUBSTR(A.CREATED_DATE,1,7) = '2022-10'
 ORDER
    BY  B.CREATED_DATE ASC, A.TITLE ASC;



SELECT b.TITLE,
       b.BOARD_ID,
       r.REPLY_ID,
       r.WRITER_ID,
       r.CONTENTS,
       DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS b
INNER 
 JOIN USED_GOODS_REPLY AS r 
   ON b.BOARD_ID = r.BOARD_ID
WHERE SUBSTR(r.CREATED_DATE, 1, 7) = '2022-10'
ORDER 
   BY r.CREATED_DATE ASC, b.TITLE ASC;


 */

/* https://school.programmers.co.kr/learn/courses/30/lessons/164673 */